import {Brand, Customers, Order, Product} from "@/assets/types.ts";

export const products: Product[] = [
    {
        id: "1",
        name: "Black Air Force",
        quantity: 12,
        price: "27,000ugx",
        category: "sneakers",
        brand: "Nike",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "789,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "2",
        name: "White Running Shoes",
        quantity: 20,
        price: "35,000ugx",
        category: "runners",
        brand: "Adidas",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "1,200,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "3",
        name: "Blue Sport Sneakers",
        quantity: 15,
        price: "30,000ugx",
        category: "sneakers",
        brand: "Puma",
        gender: "Male",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "950,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "4",
        name: "Red Basketball Shoes",
        quantity: 18,
        price: "45,000ugx",
        category: "basketball",
        brand: "Jordan",
        gender: "Male",
        size: "EUR 8",
        availability: "Limited Stock",
        date: new Date(),
        totalSales: "810,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "5",
        name: "Green Walking Shoes",
        quantity: 22,
        price: "20,000ugx",
        category: "walking",
        brand: "Reebok",
        gender: "Female",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "550,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "6",
        name: "Yellow Track Shoes",
        quantity: 10,
        price: "50,000ugx",
        category: "track",
        brand: "Under Armour",
        gender: "Female",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "1,500,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "7",
        name: "Orange High-Tops",
        quantity: 8,
        price: "60,000ugx",
        category: "high-tops",
        brand: "Converse",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "720,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "8",
        name: "Grey Cross Trainers",
        quantity: 16,
        price: "40,000ugx",
        category: "trainers",
        brand: "New Balance",
        gender: "Male",
        size: "EUR 8",
        availability: "Limited Stock",
        date: new Date(),
        totalSales: "640,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "9",
        name: "Purple Tennis Shoes",
        quantity: 13,
        price: "38,000ugx",
        category: "tennis",
        brand: "Fila",
        gender: "Female",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "494,000ugx",
        image: "/images/sports-shoe4.png"
    },
    {
        id: "10",
        name: "Brown Hiking Boots",
        quantity: 5,
        price: "70,000ugx",
        category: "hiking",
        brand: "Timberland",
        gender: "Female",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "350,000ugx",
        image: "/images/sports-shoe4.png"
    }
];

export const orders: Order[] = [
    {
        id: '1',
        product: "Brown Hiking Boots",
        customer: "Emma",
        price: "127,000ugx",
        deliveryDate: "12/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '2',
        product: "Black Air Force",
        customer: "John",
        price: "150,000ugx",
        deliveryDate: "15/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '3',
        product: "White Running Shoes",
        customer: "Sarah",
        price: "90,000ugx",
        deliveryDate: "14/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '4',
        product: "Blue Sport Sneakers",
        customer: "Michael",
        price: "110,000ugx",
        deliveryDate: "13/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '5',
        product: "Red Basketball Shoes",
        customer: "David",
        price: "180,000ugx",
        deliveryDate: "20/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '6',
        product: "Green Walking Shoes",
        customer: "Alice",
        price: "75,000ugx",
        deliveryDate: "18/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '7',
        product: "Yellow Track Shoes",
        customer: "James",
        price: "200,000ugx",
        deliveryDate: "19/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '8',
        product: "Grey Cross Trainers",
        customer: "Rebecca",
        price: "130,000ugx",
        deliveryDate: "21/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '9',
        product: "Purple Tennis Shoes",
        customer: "Chris",
        price: "95,000ugx",
        deliveryDate: "22/10/2024",
        image: "/images/boots.jpg",
    },
    {
        id: '10',
        product: "Orange High-Tops",
        customer: "Sophia",
        price: "160,000ugx",
        deliveryDate: "25/10/2024",
        image: "/images/boots.jpg",
    }
];

export const brands: Brand[] = [
    {
        id: "1",
        name: "Nike",
        country: "USA",
        established: 1964,
        category: "Sportswear Nike",
    },
    {
        id: "2",
        name: "Adidas",
        country: "Germany",
        established: 1949,
        category: "Sportswear Adidas",
    },
    {
        id: "3",
        name: "Puma",
        country: "Germany",
        established: 1948,
        category: "Sportswear Puma",
    },
    {
        id: "4",
        name: "Reebok",
        country: "USA",
        established: 1958,
        category: "Sportswear Reebok",
    },
    {
        id: "5",
        name: "Under Armour",
        country: "USA",
        established: 1996,
        category: "Sportswear Armour",
    },
    {
        id: "6",
        name: "New Balance",
        country: "USA",
        established: 1906,
        category: "Sportswear",
    },
    {
        id: "7",
        name: "Converse",
        country: "USA",
        established: 1908,
        category: "Footwear Converse",
    },
    {
        id: "8",
        name: "Timberland",
        country: "USA",
        established: 1966,
        category: "Footwear",
    }, {
        id: "8",
        name: "Fila",
        country: "USA",
        established: 1966,
        category: "Footwear",
    }, {
        id: "8",
        name: "Jordan",
        country: "USA",
        established: 1966,
        category: "Footwear",
    },

];

export const customers: Customers[] = [
    {
        id: "1",
        firstName: "Jane",
        lastName: "Smith",
        email: "jane.smith@example.com",
        password: "securePass456",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": false,
        },
    },
    {
        id: "2",
        firstName: "Michael",
        lastName: "Johnson",
        email: "michael.j@example.com",
        password: "mikePassword789",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": true,
        },
    },
    {
        id: "3",
        firstName: "Emily",
        lastName: "Davis",
        email: "emily.davis@example.com",
        password: "emilySecure321",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "4",
        firstName: "David",
        lastName: "Wilson",
        email: "david.wilson@example.com",
        password: "wilsonDavid987",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "5",
        firstName: "Sarah",
        lastName: "Brown",
        email: "sarah.brown@example.com",
        password: "sarah1234",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": true,
        },
    },
    {
        id: "6",
        firstName: "Chris",
        lastName: "Martinez",
        email: "chris.martinez@example.com",
        password: "chrisMpass456",
        permissions: {
            "add-product": false,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "7",
        firstName: "Laura",
        lastName: "Taylor",
        email: "laura.taylor@example.com",
        password: "lauraSecure789",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "8",
        firstName: "James",
        lastName: "Anderson",
        email: "james.anderson@example.com",
        password: "james456",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "9",
        firstName: "Olivia",
        lastName: "Thomas",
        email: "olivia.thomas@example.com",
        password: "oliviaPass321",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "10",
        firstName: "John",
        lastName: "Doe",
        email: "john.doe@example.com",
        password: "password123",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": false,
        },
    }
];

