import {Brand, Customers, Order, Product, Wishlist, Notification} from "@/assets/types.ts";

export const products: Product[] = [
    {
        id: "1",
        name: "Black Air Force",
        quantity: 12,
        price: "27,000ugx",
        category: "sneakers",
        brand: "Nike",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "789,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Black"
    },
    {
        id: "2",
        name: "White Running Shoes",
        quantity: 20,
        price: "35,000ugx",
        category: "runners",
        brand: "Adidas",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "1,200,000ugx",
        image: "/images/sports-shoe4.png",
        color: "White"
    },
    {
        id: "3",
        name: "Blue Sport Sneakers",
        quantity: 15,
        price: "30,000ugx",
        category: "sneakers",
        brand: "Puma",
        gender: "Male",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "950,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Blue"
    },
    {
        id: "4",
        name: "Red Basketball Shoes",
        quantity: 18,
        price: "45,000ugx",
        category: "basketball",
        brand: "Jordan",
        gender: "Male",
        size: "EUR 8",
        availability: "Limited Stock",
        date: new Date(),
        totalSales: "810,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Red"
    },
    {
        id: "5",
        name: "Green Walking Shoes",
        quantity: 22,
        price: "20,000ugx",
        category: "walking",
        brand: "Reebok",
        gender: "Female",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "550,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Green"
    },
    {
        id: "6",
        name: "Yellow Track Shoes",
        quantity: 10,
        price: "50,000ugx",
        category: "track",
        brand: "Under Armour",
        gender: "Female",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "1,500,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Yellow"
    },
    {
        id: "7",
        name: "Orange High-Tops",
        quantity: 8,
        price: "60,000ugx",
        category: "high-tops",
        brand: "Converse",
        gender: "Male",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "720,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Orange"
    },
    {
        id: "8",
        name: "Grey Cross Trainers",
        quantity: 16,
        price: "40,000ugx",
        category: "trainers",
        brand: "New Balance",
        gender: "Male",
        size: "EUR 8",
        availability: "Limited Stock",
        date: new Date(),
        totalSales: "640,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Grey"
    },
    {
        id: "9",
        name: "Purple Tennis Shoes",
        quantity: 13,
        price: "38,000ugx",
        category: "tennis",
        brand: "Fila",
        gender: "Female",
        size: "EUR 8",
        availability: "In Stock",
        date: new Date(),
        totalSales: "494,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Purple"
    },
    {
        id: "10",
        name: "Brown Hiking Boots",
        quantity: 5,
        price: "70,000ugx",
        category: "hiking",
        brand: "Timberland",
        gender: "Female",
        size: "EUR 8",
        availability: "Out of Stock",
        date: new Date(),
        totalSales: "350,000ugx",
        image: "/images/sports-shoe4.png",
        color: "Brown"
    }
];
export const orders: Order[] = [
    {
        id: '1',
        productId: "10",
        productName: "Brown Hiking Boots",
        customer: "Emma",
        status: 'IN PROGRESS',
        price: "127,000ugx",
        deliveryDate: "12/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 1,
        deliveryStatus: "Pending",
        paymentStatus: "Unpaid"
    },
    {
        id: '2',
        productId: "1",
        productName: "Black Air Force",
        customer: "John",
        status: "IN PROGRESS",
        price: "150,000ugx",
        deliveryDate: "15/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 2,
        deliveryStatus: "Pending",
        paymentStatus: "Paid"
    },
    {
        id: '3',
        productId: "2",
        productName: "White Running Shoes",
        customer: "Sarah",
        status: 'COMPLETED',
        price: "90,000ugx",
        deliveryDate: "14/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 2,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '4',
        productId: "3",
        productName: "Blue Sport Sneakers",
        customer: "Michael",
        status: "CANCELED",
        price: "110,000ugx",
        deliveryDate: "13/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 1,
        deliveryStatus: "Canceled",
        paymentStatus: "Refunded"
    },
    {
        id: '5',
        productId: "4",
        productName: "Red Basketball Shoes",
        customer: "David",
        status: "COMPLETED",
        price: "180,000ugx",
        deliveryDate: "20/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 4,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '6',
        productId: "5",
        productName: "Green Walking Shoes",
        customer: "Alice",
        status: "COMPLETED",
        price: "75,000ugx",
        deliveryDate: "18/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 3,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '7',
        productId: "6",
        productName: "Yellow Track Shoes",
        customer: "James",
        status: "COMPLETED",
        price: "200,000ugx",
        deliveryDate: "19/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 1,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '8',
        productId: "8",
        productName: "Grey Cross Trainers",
        customer: "Rebecca",
        status: "COMPLETED",
        price: "130,000ugx",
        deliveryDate: "21/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 2,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '9',
        productId: "9",
        productName: "Purple Tennis Shoes",
        customer: "Chris",
        status: "COMPLETED",
        price: "95,000ugx",
        deliveryDate: "22/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 2,
        deliveryStatus: "Delivered",
        paymentStatus: "Paid"
    },
    {
        id: '10',
        productId: "7",
        productName: "Orange High-Tops",
        customer: "Sophia",
        status: "CANCELED",
        price: "160,000ugx",
        deliveryDate: "25/10/2024",
        image: "/images/sports-shoe4.png",
        quantity: 2,
        deliveryStatus: "Canceled",
        paymentStatus: "Refunded"
    }
];

export const notifications: Notification[] = [
    {
        id: '1',
        title: 'Refine your Shoes',
        message: 'I am a full-time customer of your shoe products, but I always find a problem with the fit for my foot. Kindly work on the shoe sizes since we customers need something that fits us.',
        status: 'unread'
    },
    {
        id: '2',
        title: 'Improve Website Navigation',
        message: 'I had difficulty finding the products I wanted on your website. A better search feature would help customers locate items more quickly.',
        status: 'read'
    },
    {
        id: '3',
        title: 'Offer More Discounts',
        message: 'As a regular buyer, I would love to see more discount options, especially during holidays. It would definitely encourage more purchases from loyal customers like me.',
        status: 'unread'
    },
    {
        id: '4',
        title: 'Add Product Reviews',
        message: 'It would be helpful if there were customer reviews on your product pages so that we can make informed choices based on others’ experiences.',
        status: 'read'
    },
    {
        id: '5',
        title: 'Quality Control Feedback',
        message: 'I recently received a product with minor defects. Please improve quality checks to ensure every item meets high standards before shipping.',
        status: 'unread'
    },
    {
        id: '6',
        title: 'Consider Faster Shipping Options',
        message: 'Shipping took longer than expected for my last order. It would be great if there were an option for faster delivery, even at an extra cost.',
        status: 'read'
    },
    {
        id: '7',
        title: 'Improve Mobile App Performance',
        message: 'The app sometimes lags on my phone, making it difficult to browse products. Optimizing it for speed would enhance the shopping experience.',
        status: 'unread'
    },
    {
        id: '8',
        title: 'Expand Product Categories',
        message: 'I would love to see a wider range of products in the store, especially in the electronics category. It would save me from shopping on multiple platforms.',
        status: 'read'
    },
    {
        id: '9',
        title: 'Email Subscription Preferences',
        message: 'I receive too many promotional emails. It would be better if I could choose the types and frequency of emails to receive from your brand.',
        status: 'unread'
    },
    {
        id: '10',
        title: 'More Payment Options',
        message: 'It would be convenient if more payment options were available, like digital wallets or pay-on-delivery, to make the shopping experience easier.',
        status: 'read'
    }
];

export const wishlist: Wishlist[] = [
    {
        id: "1",
        productId: "2",
        name: "White Running Shoes",
        category: "runners",
        brand: "Adidas",
        price: "35,000ugx",
        color: "White",
        size: "M",
        quantity: 1,
        total: "35,000ugx",
        addedDate: new Date(),
        priority: "High",
        image: "/images/sports-shoe4.png",
    },
    {
        id: "2",
        productId: "4",
        name: "Red Basketball Shoes",
        category: "basketball",
        brand: "Jordan",
        price: "45,000ugx",
        color: "Red",
        size: "L",
        quantity: 2,
        total: "90,000ugx",
        addedDate: new Date(),
        priority: "Medium",
        userNotes: "Great for training sessions",
        image: "/images/sports-shoe4.png",
    },
    {
        id: "3",
        productId: "5",
        name: "Green Walking Shoes",
        category: "walking",
        brand: "Reebok",
        price: "20,000ugx",
        color: "Green",
        size: "S",
        quantity: 1,
        total: "20,000ugx",
        addedDate: new Date(),
        priority: "Low",
        userNotes: "Comfortable for everyday wear",
        image: "/images/sports-shoe4.png",
    },
    {
        id: "4",
        productId: "7",
        name: "Orange High-Tops",
        category: "high-tops",
        brand: "Converse",
        price: "60,000ugx",
        color: "Orange",
        size: "M",
        quantity: 1,
        total: "60,000ugx",
        addedDate: new Date(),
        priority: "High",
        userNotes: "Stylish addition to the wardrobe",
        image: "/images/sports-shoe4.png",
    },
    {
        id: "5",
        productId: "10",
        name: "Brown Hiking Boots",
        category: "hiking",
        brand: "Timberland",
        price: "70,000ugx",
        color: "Brown",
        size: "L",
        quantity: 1,
        total: "70,000ugx",
        addedDate: new Date(),
        priority: "Medium",
        userNotes: "Essential for outdoor activities",
        image: "/images/sports-shoe4.png",
    }
];

export const brands: Brand[] = [
    {
        id: "1",
        name: "Nike",
        country: "USA",
        established: 1964,
        category: "Sportswear Nike",
    },
    {
        id: "2",
        name: "Adidas",
        country: "Germany",
        established: 1949,
        category: "Sportswear Adidas",
    },
    {
        id: "3",
        name: "Puma",
        country: "Germany",
        established: 1948,
        category: "Sportswear Puma",
    },
    {
        id: "4",
        name: "Reebok",
        country: "USA",
        established: 1958,
        category: "Sportswear Reebok",
    },
    {
        id: "5",
        name: "Under Armour",
        country: "USA",
        established: 1996,
        category: "Sportswear Armour",
    },
    {
        id: "6",
        name: "New Balance",
        country: "USA",
        established: 1906,
        category: "Sportswear",
    },
    {
        id: "7",
        name: "Converse",
        country: "USA",
        established: 1908,
        category: "Footwear Converse",
    },
    {
        id: "8",
        name: "Timberland",
        country: "USA",
        established: 1966,
        category: "Footwear",
    }, {
        id: "8",
        name: "Fila",
        country: "USA",
        established: 1966,
        category: "Footwear",
    }, {
        id: "8",
        name: "Jordan",
        country: "USA",
        established: 1966,
        category: "Footwear",
    },

];

export const customers: Customers[] = [
    {
        id: "1",
        firstName: "Jane",
        lastName: "Smith",
        email: "jane.smith@example.com",
        password: "securePass456",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": false,
        },
    },
    {
        id: "2",
        firstName: "Michael",
        lastName: "Johnson",
        email: "michael.j@example.com",
        password: "mikePassword789",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": true,
        },
    },
    {
        id: "3",
        firstName: "Emily",
        lastName: "Davis",
        email: "emily.davis@example.com",
        password: "emilySecure321",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "4",
        firstName: "David",
        lastName: "Wilson",
        email: "david.wilson@example.com",
        password: "wilsonDavid987",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "5",
        firstName: "Sarah",
        lastName: "Brown",
        email: "sarah.brown@example.com",
        password: "sarah1234",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": true,
        },
    },
    {
        id: "6",
        firstName: "Chris",
        lastName: "Martinez",
        email: "chris.martinez@example.com",
        password: "chrisMpass456",
        permissions: {
            "add-product": false,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "7",
        firstName: "Laura",
        lastName: "Taylor",
        email: "laura.taylor@example.com",
        password: "lauraSecure789",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "8",
        firstName: "James",
        lastName: "Anderson",
        email: "james.anderson@example.com",
        password: "james456",
        permissions: {
            "add-product": true,
            "update-product": false,
            "delete-product": true,
        },
    },
    {
        id: "9",
        firstName: "Olivia",
        lastName: "Thomas",
        email: "olivia.thomas@example.com",
        password: "oliviaPass321",
        permissions: {
            "add-product": false,
            "update-product": true,
            "delete-product": false,
        },
    },
    {
        id: "10",
        firstName: "John",
        lastName: "Doe",
        email: "john.doe@example.com",
        password: "password123",
        permissions: {
            "add-product": true,
            "update-product": true,
            "delete-product": false,
        },
    }
];

export const paymentStatus =  ["Paid", "Unpaid", "Refunded"]
export const orderStatus = ["CANCELED", "COMPLETED", "IN PROGRESS"]
export const deliveryStatus = ["Pending", "Delivered", "Canceled"]
